name: habari_pay_cs
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  dio:
  intl:
  path:
  tuple:
  logger:
  sqflite:
  equatable:
  flutter_svg:
  flutter_bloc:
  flutter_dotenv:
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  bloc_test: ^9.1.5
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env.development
